from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s


class Ui_Scrabble(object):
    def setupUi(self, Scrabble):
        Scrabble.setObjectName(_fromUtf8("Scrabble"))
        Scrabble.resize(1341, 1003)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Scrabble.setFont(font)
        Scrabble.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\nbackground-color: rgb(67, 67, 67);"))
        self.centralwidget = QtGui.QWidget(Scrabble)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        # self.centralwidget.setAutoFillBackground(False)
        # self.centralwidget.setObjectName(_fromUtf8("centralwidget"))

        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 11, 11, -1)
        self.gridLayout.setSpacing(15)
        # self.gridLayout.setObjectName(_fromUtf8("gridLayout"))

        self.verticalLayout_2 = QtGui.QVBoxLayout()
        # self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))

        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.ques = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stencil"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ques.setFont(font)
        self.ques.setStyleSheet(_fromUtf8("background-color: rgb(55, 165, 165);"))
        # self.ques.setLineWidth(1)
        self.ques.setAlignment(QtCore.Qt.AlignCenter)
        self.ques.setWordWrap(True)
        self.ques.setObjectName(_fromUtf8("ques"))
        self.ques.setText("CHOOSE YOUR LETTER")
        self.verticalLayout_2.addWidget(self.ques)

        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)

        self.player = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stencil"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.player.setFont(font)
        self.player.setStyleSheet(_fromUtf8("background-color: rgb(55, 165, 165);"))
        self.player.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.player.setObjectName(_fromUtf8("player"))
        self.player.setText("PLAYER 1")
        self.verticalLayout_2.addWidget(self.player)

        self.scorecard = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stencil"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.scorecard.setFont(font)
        self.scorecard.setStyleSheet(_fromUtf8("background-color: rgb(55, 165, 165);"))
        self.scorecard.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.scorecard.setObjectName(_fromUtf8("scorecard"))
        self.scorecard.setText("SCORE = 0")
        self.verticalLayout_2.addWidget(self.scorecard)

        self.tiles = QtGui.QTableWidget(self.centralwidget)
        self.tiles.setMaximumSize(QtCore.QSize(480, 125))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tiles.setFont(font)
        self.tiles.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tiles.setFrameShadow(QtGui.QFrame.Raised)
        self.tiles.setLineWidth(1)

        self.tiles.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tiles.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tiles.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tiles.setShowGrid(True)
        self.tiles.setGridStyle(QtCore.Qt.SolidLine)
        self.tiles.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tiles.setWordWrap(True)
        self.tiles.setCornerButtonEnabled(True)
        self.tiles.setColumnCount(7)
        self.tiles.setObjectName(_fromUtf8("tiles"))
        self.tiles.setRowCount(2)

        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)

        self.tiles.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)

        self.tiles.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tiles.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tiles.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tiles.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tiles.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tiles.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tiles.setHorizontalHeaderItem(5, item)

        self.tiles.horizontalHeader().setVisible(False)
        self.tiles.horizontalHeader().setCascadingSectionResizes(True)
        self.tiles.horizontalHeader().setDefaultSectionSize(60)
        self.tiles.horizontalHeader().setHighlightSections(True)
        self.tiles.horizontalHeader().setMinimumSectionSize(40)
        self.tiles.horizontalHeader().setStretchLastSection(False)
        self.tiles.verticalHeader().setCascadingSectionResizes(True)
        self.tiles.verticalHeader().setDefaultSectionSize(60)
        self.tiles.verticalHeader().setHighlightSections(True)
        self.tiles.verticalHeader().setMinimumSectionSize(40)
        self.tiles.verticalHeader().setSortIndicatorShown(False)
        self.tiles.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tiles)

        self.done = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done.sizePolicy().hasHeightForWidth())
        self.done.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.done.setFont(font)
        self.done.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.done.setStyleSheet(_fromUtf8("background-color: rgb(55, 165, 165);"))
        self.done.setIconSize(QtCore.QSize(20, 20))
        self.done.setObjectName(_fromUtf8("done"))
        self.verticalLayout_2.addWidget(self.done)

        self.player2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stencil"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.player2.setFont(font)
        self.player2.setStyleSheet(_fromUtf8("background-color: rgb(55, 165, 165);"))
        self.player2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.player2.setObjectName(_fromUtf8("player2"))
        self.player2.setText("PLAYER 2")
        self.verticalLayout_2.addWidget(self.player2)

        self.scorecard2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stencil"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.scorecard2.setFont(font)
        self.scorecard2.setStyleSheet(_fromUtf8("background-color: rgb(55, 165, 165);"))
        self.scorecard2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.scorecard2.setObjectName(_fromUtf8("scorecard2"))
        self.scorecard2.setText("SCORE = 0")
        self.verticalLayout_2.addWidget(self.scorecard2)

        self.tiles2 = QtGui.QTableWidget(self.centralwidget)
        self.tiles2.setMaximumSize(QtCore.QSize(480, 125))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tiles2.setFont(font)
        self.tiles2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tiles2.setFrameShadow(QtGui.QFrame.Raised)
        self.tiles2.setLineWidth(1)

        self.tiles2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tiles2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tiles2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tiles2.setShowGrid(True)
        self.tiles2.setGridStyle(QtCore.Qt.SolidLine)
        self.tiles2.setWordWrap(True)
        self.tiles2.setCornerButtonEnabled(True)
        self.tiles2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tiles2.setColumnCount(7)
        self.tiles2.setObjectName(_fromUtf8("tiles2"))
        self.tiles2.setRowCount(2)

        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)

        self.tiles2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)

        self.tiles2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tiles2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tiles2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tiles2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tiles2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tiles2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tiles2.setHorizontalHeaderItem(5, item)

        self.tiles2.horizontalHeader().setVisible(False)
        self.tiles2.horizontalHeader().setCascadingSectionResizes(True)
        self.tiles2.horizontalHeader().setDefaultSectionSize(60)
        self.tiles2.horizontalHeader().setHighlightSections(True)
        self.tiles2.horizontalHeader().setMinimumSectionSize(40)
        self.tiles2.horizontalHeader().setStretchLastSection(False)
        self.tiles2.verticalHeader().setCascadingSectionResizes(True)
        self.tiles2.verticalHeader().setDefaultSectionSize(60)
        self.tiles2.verticalHeader().setHighlightSections(True)
        self.tiles2.verticalHeader().setMinimumSectionSize(40)
        self.tiles2.verticalHeader().setSortIndicatorShown(False)
        self.tiles2.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tiles2)

        self.done2 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done2.sizePolicy().hasHeightForWidth())
        self.done2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.done2.setFont(font)
        self.done2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.done2.setStyleSheet(_fromUtf8("background-color: rgb(55, 165, 165);"))
        self.done2.setIconSize(QtCore.QSize(20, 20))
        self.done2.setObjectName(_fromUtf8("done2"))
        self.verticalLayout_2.addWidget(self.done2)

        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)

        self.board = QtGui.QTableWidget(self.centralwidget)
        self.board.setMaximumSize(QtCore.QSize(782, 782))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.board.setFont(font)
        self.board.setAutoFillBackground(False)
        self.board.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.board.setFrameShape(QtGui.QFrame.StyledPanel)
        self.board.setFrameShadow(QtGui.QFrame.Raised)
        self.board.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.board.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.board.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.board.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.board.setObjectName(_fromUtf8("board"))
        self.board.setColumnCount(15)
        self.board.setRowCount(15)

        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.board.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.board.setHorizontalHeaderItem(14, item)

        for i in range(1, 14):
            for j in range(1, 14):
                item = QtGui.QTableWidgetItem()
                item.setText("")
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                if i == j or i + j == 14:
                    if i == 6 or i == 8:
                        brush = QtGui.QBrush(QtGui.QColor(75, 225, 225))
                        brush.setStyle(QtCore.Qt.SolidPattern)
                        item.setBackground(brush)
                    elif i == 5 or i == 9:
                        brush = QtGui.QBrush(QtGui.QColor(50, 140, 140, 200))
                        brush.setStyle(QtCore.Qt.SolidPattern)
                        item.setBackground(brush)
                    else:
                        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
                        brush.setStyle(QtCore.Qt.SolidPattern)
                        item.setBackground(brush)
                else:
                    if i+4 == j or i + j == 10:
                        if i in [1, 5, 9, 13]:
                            brush = QtGui.QBrush(QtGui.QColor(50, 140, 140, 200))
                            brush.setStyle(QtCore.Qt.SolidPattern)
                            item.setBackground(brush)
                        else:
                            if i not in [4, 6, 10]:
                                brush = QtGui.QBrush(QtGui.QColor(75, 225, 225))
                                brush.setStyle(QtCore.Qt.SolidPattern)
                                item.setBackground(brush)
                    if i == j+4 or i + j == 18:
                        if i in [1, 5, 9, 13]:
                            brush = QtGui.QBrush(QtGui.QColor(50, 140, 140, 200))
                            brush.setStyle(QtCore.Qt.SolidPattern)
                            item.setBackground(brush)
                        else:
                            if i not in [4, 8, 10]:
                                brush = QtGui.QBrush(QtGui.QColor(75, 225, 225))
                                brush.setStyle(QtCore.Qt.SolidPattern)
                                item.setBackground(brush)

                self.board.setItem(i, j, item)
        for i in range(0, 15, 14):
            for j in range(0, 15):
                item = QtGui.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                item2 = QtGui.QTableWidgetItem()
                item2.setTextAlignment(QtCore.Qt.AlignCenter)
                if j in [0, 7, 14]:
                    brush = QtGui.QBrush(QtGui.QColor(255, 170, 130))
                    brush.setStyle(QtCore.Qt.SolidPattern)
                    item2.setBackground(brush)
                    item.setBackground(brush)
                if j in [3, 11]:
                    brush = QtGui.QBrush(QtGui.QColor(75, 225, 225))
                    brush.setStyle(QtCore.Qt.SolidPattern)
                    item2.setBackground(brush)
                    item.setBackground(brush)
                self.board.setItem(i, j, item)
                self.board.setItem(j, i, item2)
        item = self.board.item(7, 7)
        item.setText("XX")
        self.board.setItem(7, 7, item)

        self.board.horizontalHeader().setDefaultSectionSize(50)
        self.board.horizontalHeader().setMinimumSectionSize(40)
        self.board.verticalHeader().setDefaultSectionSize(50)
        self.board.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout.addWidget(self.board, 1, 0, 1, 1)

        self.heading = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Jokerman"))
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName(_fromUtf8("heading"))
        self.gridLayout.addWidget(self.heading, 0, 0, 1, 2)

        self.gridLayout.setColumnStretch(0, 8)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 7)
        Scrabble.setCentralWidget(self.centralwidget)

        self.menubar = QtGui.QMenuBar(Scrabble)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1341, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 67, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.menubar.setPalette(palette)

        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        Scrabble.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Scrabble)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Scrabble.setStatusBar(self.statusbar)
        self.actionSave_As = QtGui.QAction(Scrabble)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionOpen = QtGui.QAction(Scrabble)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionNew_Game = QtGui.QAction(Scrabble)
        self.actionNew_Game.setObjectName(_fromUtf8("actionNew_Game"))
        self.actionQuit = QtGui.QAction(Scrabble)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRules = QtGui.QAction(Scrabble)
        self.actionRules.setObjectName(_fromUtf8("actionRules"))
        self.actionWord_Hint = QtGui.QAction(Scrabble)
        self.actionWord_Hint.setObjectName(_fromUtf8("actionWord_Hint"))
        self.actionScore_Card = QtGui.QAction(Scrabble)
        self.actionScore_Card.setObjectName(_fromUtf8("actionScore_Card"))
        self.actionNo_Of_Tiles_Left = QtGui.QAction(Scrabble)
        self.actionNo_Of_Tiles_Left.setObjectName(_fromUtf8("actionNo_Of_Tiles_Left"))
        self.actionWord_Check = QtGui.QAction(Scrabble)
        self.actionWord_Check.setObjectName(_fromUtf8("actionWord_Check"))
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionRules)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWord_Hint)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWord_Check)
        self.menuView.addAction(self.actionScore_Card)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionNo_Of_Tiles_Left)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.heading.setText("Let's Play Scrabble")
        Scrabble.setWindowTitle("Scrabble")
        item = self.tiles.verticalHeaderItem(0)
        item.setText("Tile   ")
        item = self.tiles.verticalHeaderItem(1)
        item.setText("Score     ")
        self.done.setText("Done")
        item = self.tiles2.verticalHeaderItem(0)
        item.setText("Tile   ")
        item = self.tiles2.verticalHeaderItem(1)
        item.setText("Score     ")
        self.done2.setText("Done")

        for i in range(0, 15):
            item = self.board.verticalHeaderItem(i)
            item.setText(str(i + 1))
            item = self.board.horizontalHeaderItem(i)
            item.setText(str(i + 1))

        self.menuFile.setTitle("File")
        self.menuHelp.setTitle("Help")
        self.menuView.setTitle("View")
        self.actionSave_As.setText("Save As")
        self.actionSave_As.setShortcut(QtGui.QKeySequence("Ctrl+S"))
        self.actionSave_As.setStatusTip("SAVE THE GAME AT IT'S CURRENT POSITION")

        self.actionOpen.setText("Open")
        self.actionOpen.setShortcut(QtGui.QKeySequence("Ctrl+O"))
        self.actionOpen.setStatusTip("OPEN A PREVIOUSLY SAVED GAME")

        self.actionNew_Game.setText("New Game")
        self.actionNew_Game.setShortcut(QtGui.QKeySequence("Ctrl+N"))
        self.actionNew_Game.setStatusTip("START A NEW GAME")

        self.actionQuit.setText("Quit")
        self.actionQuit.setShortcut(QtGui.QKeySequence("Ctrl+Q"))
        self.actionQuit.setStatusTip("EXIT THE GAME")

        self.actionRules.setText("Rules")
        self.actionRules.setShortcut(QtGui.QKeySequence("Ctrl+R"))
        self.actionRules.setStatusTip("SCRABBLE RULES")

        self.actionWord_Hint.setText("Word Hint")
        self.actionWord_Hint.setShortcut(QtGui.QKeySequence("Ctrl+H"))
        self.actionWord_Hint.setStatusTip("HINT")

        self.actionScore_Card.setText("Score Card")
        self.actionScore_Card.setShortcut(QtGui.QKeySequence("Ctrl+C"))
        self.actionScore_Card.setStatusTip("SCORE CARD")

        self.actionNo_Of_Tiles_Left.setText("Tiles")
        self.actionNo_Of_Tiles_Left.setShortcut(QtGui.QKeySequence("Ctrl+T"))
        self.actionNo_Of_Tiles_Left.setStatusTip("TILES LEFT")

        self.actionWord_Check.setText("Word Check")
        self.actionWord_Check.setShortcut(QtGui.QKeySequence("Ctrl+W"))
        self.actionWord_Check.setStatusTip("WORD CHECK")

        Scrabble.show()
        QtCore.QMetaObject.connectSlotsByName(Scrabble)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Scrabble = QtGui.QMainWindow()
    ui = Ui_Scrabble()
    ui.setupUi(Scrabble)
    Scrabble.show()
    sys.exit(app.exec_())
